### ISSUE TITLE
settings.yamlの書式を決める

### ISSUE THREAD

**Issue by yassi-github** [higuruchi/injesh#44]
実行コマンドだけでなく、#41 にあるように、docker contanier idのメモなどの機能もほしい

**Comment by yassi-github** [comment]
案1

```yaml
# デバッグ対象のコンテナID
docker_container_id: abc123
# 利用するシェル
shell: bash
# 利用するコマンド
commands:
    - ls
    - cp
    - mv
```
